# Things in {{CURLIES}} will be read from the process environment when the server starts up.
# The jrun launcher will typically load these from ~/.dns.env

serverName: cloudos-dns

#publicUriBase: https://127.0.0.1
publicUriBase: {{PUBLIC_BASE_URI}}

bcryptRounds: 16
springContextPath: classpath:/spring.xml

dataKey: {{SESSION_DATAKEY}}

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://{{CLOUDOS_DNS_DB_HOST}}:{{CLOUDOS_DNS_DB_PORT}}/{{CLOUDOS_DNS_DB_NAME}}
  user: {{CLOUDOS_DNS_DB_USER}}
  password: {{CLOUDOS_DNS_DB_PASS}}

  hibernate:
    entityPackages: [ cloudos.dns.model ]
    dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hbm2ddlAuto: validate
    validationMode: ddl

http:
  port: {{CLOUDOS_DNS_SERVER_PORT}}
  baseUri: /api

jersey:
  resourcePackages:
  - cloudos.dns.resources
  - org.cobbzilla.wizard.server
  - org.cobbzilla.wizard.filters
  - org.cobbzilla.wizard.exceptionmappers
  responseFilters: [ org.cobbzilla.wizard.filters.ScrubbableScrubber ]

serverType: {{DNS_MODE}}

{{#DNS_DJBDNS}}
rooty:
  queueName: {{ROOTY_QUEUE_NAME}} # matches where rooty reads from, defined in /etc/rooty/*.yml (from cloudstead chef recipe)
  secret: {{ROOTY_SECRET}}        # used to generate hashes in request filenames
  handlers:
    {{DNS_HANDLER}}:
{{/DNS_DJBDNS}}

{{#DNS_DYN}}
dyndns:
  account: {{DYNDNS_ACCOUNT}}
  user: {{DYNDNS_USER}}
  password: {{DYNDNS_PASSWORD}}
  zone: {{DYNDNS_ZONE}}
{{/DNS_DYN}}